//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FnR.WebApi.eWay.Token {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", ConfigurationName="eWay.Token.managedCreditCardPaymentSoap")]
    public interface managedCreditCardPaymentSoap {
        
        // CODEGEN: Generating message contract since message CreateCustomerRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/CreateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManagedCustomer))]
        FnR.WebApi.eWay.Token.CreateCustomerResponse CreateCustomer(FnR.WebApi.eWay.Token.CreateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/CreateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.CreateCustomerResponse> CreateCustomerAsync(FnR.WebApi.eWay.Token.CreateCustomerRequest request);
        
        // CODEGEN: Generating message contract since message UpdateCustomerRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/UpdateCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManagedCustomer))]
        FnR.WebApi.eWay.Token.UpdateCustomerResponse UpdateCustomer(FnR.WebApi.eWay.Token.UpdateCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/UpdateCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.UpdateCustomerResponse> UpdateCustomerAsync(FnR.WebApi.eWay.Token.UpdateCustomerRequest request);
        
        // CODEGEN: Generating message contract since message QueryCustomerRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/QueryCustomer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManagedCustomer))]
        FnR.WebApi.eWay.Token.QueryCustomerResponse QueryCustomer(FnR.WebApi.eWay.Token.QueryCustomerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/QueryCustomer", ReplyAction="*")]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryCustomerResponse> QueryCustomerAsync(FnR.WebApi.eWay.Token.QueryCustomerRequest request);
        
        // CODEGEN: Generating message contract since message QueryCustomerByReferenceRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/QueryCustomerByReference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManagedCustomer))]
        FnR.WebApi.eWay.Token.QueryCustomerByReferenceResponse QueryCustomerByReference(FnR.WebApi.eWay.Token.QueryCustomerByReferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/QueryCustomerByReference", ReplyAction="*")]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryCustomerByReferenceResponse> QueryCustomerByReferenceAsync(FnR.WebApi.eWay.Token.QueryCustomerByReferenceRequest request);
        
        // CODEGEN: Generating message contract since message ProcessPaymentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/ProcessPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManagedCustomer))]
        FnR.WebApi.eWay.Token.ProcessPaymentResponse ProcessPayment(FnR.WebApi.eWay.Token.ProcessPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/ProcessPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentResponse> ProcessPaymentAsync(FnR.WebApi.eWay.Token.ProcessPaymentRequest request);
        
        // CODEGEN: Generating message contract since message ProcessPaymentWithBeagleRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/ProcessPaymentWithBeagle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManagedCustomer))]
        FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleResponse ProcessPaymentWithBeagle(FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/ProcessPaymentWithBeagle", ReplyAction="*")]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleResponse> ProcessPaymentWithBeagleAsync(FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleRequest request);
        
        // CODEGEN: Generating message contract since message ProcessPaymentWithCVNRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/ProcessPaymentWithCVN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManagedCustomer))]
        FnR.WebApi.eWay.Token.ProcessPaymentWithCVNResponse ProcessPaymentWithCVN(FnR.WebApi.eWay.Token.ProcessPaymentWithCVNRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/ProcessPaymentWithCVN", ReplyAction="*")]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentWithCVNResponse> ProcessPaymentWithCVNAsync(FnR.WebApi.eWay.Token.ProcessPaymentWithCVNRequest request);
        
        // CODEGEN: Generating message contract since message QueryPaymentRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/QueryPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManagedCustomer))]
        FnR.WebApi.eWay.Token.QueryPaymentResponse QueryPayment(FnR.WebApi.eWay.Token.QueryPaymentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.eway.com.au/gateway/managedpayment/QueryPayment", ReplyAction="*")]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryPaymentResponse> QueryPaymentAsync(FnR.WebApi.eWay.Token.QueryPaymentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
    public partial class eWAYHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eWAYCustomerIDField;
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string eWAYCustomerID {
            get {
                return this.eWAYCustomerIDField;
            }
            set {
                this.eWAYCustomerIDField = value;
                this.RaisePropertyChanged("eWAYCustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
    public partial class ManagedTransaction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int totalAmountField;
        
        private int resultField;
        
        private string responseTextField;
        
        private System.DateTime transactionDateField;
        
        private int ewayTrxnNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("TotalAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResponseText {
            get {
                return this.responseTextField;
            }
            set {
                this.responseTextField = value;
                this.RaisePropertyChanged("ResponseText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
                this.RaisePropertyChanged("TransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ewayTrxnNumber {
            get {
                return this.ewayTrxnNumberField;
            }
            set {
                this.ewayTrxnNumberField = value;
                this.RaisePropertyChanged("ewayTrxnNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
    public partial class CCPaymentResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ewayTrxnErrorField;
        
        private string ewayTrxnStatusField;
        
        private string ewayTrxnNumberField;
        
        private string ewayReturnAmountField;
        
        private string ewayAuthCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ewayTrxnError {
            get {
                return this.ewayTrxnErrorField;
            }
            set {
                this.ewayTrxnErrorField = value;
                this.RaisePropertyChanged("ewayTrxnError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ewayTrxnStatus {
            get {
                return this.ewayTrxnStatusField;
            }
            set {
                this.ewayTrxnStatusField = value;
                this.RaisePropertyChanged("ewayTrxnStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ewayTrxnNumber {
            get {
                return this.ewayTrxnNumberField;
            }
            set {
                this.ewayTrxnNumberField = value;
                this.RaisePropertyChanged("ewayTrxnNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ewayReturnAmount {
            get {
                return this.ewayReturnAmountField;
            }
            set {
                this.ewayReturnAmountField = value;
                this.RaisePropertyChanged("ewayReturnAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ewayAuthCode {
            get {
                return this.ewayAuthCodeField;
            }
            set {
                this.ewayAuthCodeField = value;
                this.RaisePropertyChanged("ewayAuthCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditCard))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
    public partial class ManagedCustomer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long managedCustomerIDField;
        
        private string customerRefField;
        
        private string customerTitleField;
        
        private string customerFirstNameField;
        
        private string customerLastNameField;
        
        private string customerCompanyField;
        
        private string customerJobDescField;
        
        private string customerEmailField;
        
        private string customerAddressField;
        
        private string customerSuburbField;
        
        private string customerStateField;
        
        private string customerPostCodeField;
        
        private string customerCountryField;
        
        private string customerPhone1Field;
        
        private string customerPhone2Field;
        
        private string customerFaxField;
        
        private string customerURLField;
        
        private string customerCommentsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ManagedCustomerID {
            get {
                return this.managedCustomerIDField;
            }
            set {
                this.managedCustomerIDField = value;
                this.RaisePropertyChanged("ManagedCustomerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CustomerRef {
            get {
                return this.customerRefField;
            }
            set {
                this.customerRefField = value;
                this.RaisePropertyChanged("CustomerRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CustomerTitle {
            get {
                return this.customerTitleField;
            }
            set {
                this.customerTitleField = value;
                this.RaisePropertyChanged("CustomerTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CustomerFirstName {
            get {
                return this.customerFirstNameField;
            }
            set {
                this.customerFirstNameField = value;
                this.RaisePropertyChanged("CustomerFirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CustomerLastName {
            get {
                return this.customerLastNameField;
            }
            set {
                this.customerLastNameField = value;
                this.RaisePropertyChanged("CustomerLastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CustomerCompany {
            get {
                return this.customerCompanyField;
            }
            set {
                this.customerCompanyField = value;
                this.RaisePropertyChanged("CustomerCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomerJobDesc {
            get {
                return this.customerJobDescField;
            }
            set {
                this.customerJobDescField = value;
                this.RaisePropertyChanged("CustomerJobDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CustomerEmail {
            get {
                return this.customerEmailField;
            }
            set {
                this.customerEmailField = value;
                this.RaisePropertyChanged("CustomerEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CustomerAddress {
            get {
                return this.customerAddressField;
            }
            set {
                this.customerAddressField = value;
                this.RaisePropertyChanged("CustomerAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CustomerSuburb {
            get {
                return this.customerSuburbField;
            }
            set {
                this.customerSuburbField = value;
                this.RaisePropertyChanged("CustomerSuburb");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CustomerState {
            get {
                return this.customerStateField;
            }
            set {
                this.customerStateField = value;
                this.RaisePropertyChanged("CustomerState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CustomerPostCode {
            get {
                return this.customerPostCodeField;
            }
            set {
                this.customerPostCodeField = value;
                this.RaisePropertyChanged("CustomerPostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CustomerCountry {
            get {
                return this.customerCountryField;
            }
            set {
                this.customerCountryField = value;
                this.RaisePropertyChanged("CustomerCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CustomerPhone1 {
            get {
                return this.customerPhone1Field;
            }
            set {
                this.customerPhone1Field = value;
                this.RaisePropertyChanged("CustomerPhone1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string CustomerPhone2 {
            get {
                return this.customerPhone2Field;
            }
            set {
                this.customerPhone2Field = value;
                this.RaisePropertyChanged("CustomerPhone2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string CustomerFax {
            get {
                return this.customerFaxField;
            }
            set {
                this.customerFaxField = value;
                this.RaisePropertyChanged("CustomerFax");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string CustomerURL {
            get {
                return this.customerURLField;
            }
            set {
                this.customerURLField = value;
                this.RaisePropertyChanged("CustomerURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string CustomerComments {
            get {
                return this.customerCommentsField;
            }
            set {
                this.customerCommentsField = value;
                this.RaisePropertyChanged("CustomerComments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18046")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
    public partial class CreditCard : ManagedCustomer {
        
        private string cCNameField;
        
        private string cCNumberField;
        
        private string cCExpiryMonthField;
        
        private string cCExpiryYearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CCName {
            get {
                return this.cCNameField;
            }
            set {
                this.cCNameField = value;
                this.RaisePropertyChanged("CCName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CCNumber {
            get {
                return this.cCNumberField;
            }
            set {
                this.cCNumberField = value;
                this.RaisePropertyChanged("CCNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CCExpiryMonth {
            get {
                return this.cCExpiryMonthField;
            }
            set {
                this.cCExpiryMonthField = value;
                this.RaisePropertyChanged("CCExpiryMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CCExpiryYear {
            get {
                return this.cCExpiryYearField;
            }
            set {
                this.cCExpiryYearField = value;
                this.RaisePropertyChanged("CCExpiryYear");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCustomer", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class CreateCustomerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
        public FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=1)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=2)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=3)]
        public string Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=4)]
        public string Suburb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=5)]
        public string State;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=6)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=7)]
        public string PostCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=8)]
        public string Country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=9)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=10)]
        public string Fax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=11)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=12)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=13)]
        public string CustomerRef;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=14)]
        public string JobDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=15)]
        public string Comments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=16)]
        public string URL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=17)]
        public string CCNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=18)]
        public string CCNameOnCard;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=19)]
        public int CCExpiryMonth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=20)]
        public int CCExpiryYear;
        
        public CreateCustomerRequest() {
        }
        
        public CreateCustomerRequest(
                    FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, 
                    string Title, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string Suburb, 
                    string State, 
                    string Company, 
                    string PostCode, 
                    string Country, 
                    string Email, 
                    string Fax, 
                    string Phone, 
                    string Mobile, 
                    string CustomerRef, 
                    string JobDesc, 
                    string Comments, 
                    string URL, 
                    string CCNumber, 
                    string CCNameOnCard, 
                    int CCExpiryMonth, 
                    int CCExpiryYear) {
            this.eWAYHeader = eWAYHeader;
            this.Title = Title;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Address = Address;
            this.Suburb = Suburb;
            this.State = State;
            this.Company = Company;
            this.PostCode = PostCode;
            this.Country = Country;
            this.Email = Email;
            this.Fax = Fax;
            this.Phone = Phone;
            this.Mobile = Mobile;
            this.CustomerRef = CustomerRef;
            this.JobDesc = JobDesc;
            this.Comments = Comments;
            this.URL = URL;
            this.CCNumber = CCNumber;
            this.CCNameOnCard = CCNameOnCard;
            this.CCExpiryMonth = CCExpiryMonth;
            this.CCExpiryYear = CCExpiryYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCustomerResponse", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class CreateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public string CreateCustomerResult;
        
        public CreateCustomerResponse() {
        }
        
        public CreateCustomerResponse(string CreateCustomerResult) {
            this.CreateCustomerResult = CreateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomer", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class UpdateCustomerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
        public FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public long managedCustomerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=1)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=2)]
        public string FirstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=3)]
        public string LastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=4)]
        public string Address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=5)]
        public string Suburb;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=6)]
        public string State;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=7)]
        public string Company;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=8)]
        public string PostCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=9)]
        public string Country;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=10)]
        public string Email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=11)]
        public string Fax;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=12)]
        public string Phone;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=13)]
        public string Mobile;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=14)]
        public string CustomerRef;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=15)]
        public string JobDesc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=16)]
        public string Comments;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=17)]
        public string URL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=18)]
        public string CCNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=19)]
        public string CCNameOnCard;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=20)]
        public int CCExpiryMonth;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=21)]
        public int CCExpiryYear;
        
        public UpdateCustomerRequest() {
        }
        
        public UpdateCustomerRequest(
                    FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, 
                    long managedCustomerID, 
                    string Title, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string Suburb, 
                    string State, 
                    string Company, 
                    string PostCode, 
                    string Country, 
                    string Email, 
                    string Fax, 
                    string Phone, 
                    string Mobile, 
                    string CustomerRef, 
                    string JobDesc, 
                    string Comments, 
                    string URL, 
                    string CCNumber, 
                    string CCNameOnCard, 
                    int CCExpiryMonth, 
                    int CCExpiryYear) {
            this.eWAYHeader = eWAYHeader;
            this.managedCustomerID = managedCustomerID;
            this.Title = Title;
            this.FirstName = FirstName;
            this.LastName = LastName;
            this.Address = Address;
            this.Suburb = Suburb;
            this.State = State;
            this.Company = Company;
            this.PostCode = PostCode;
            this.Country = Country;
            this.Email = Email;
            this.Fax = Fax;
            this.Phone = Phone;
            this.Mobile = Mobile;
            this.CustomerRef = CustomerRef;
            this.JobDesc = JobDesc;
            this.Comments = Comments;
            this.URL = URL;
            this.CCNumber = CCNumber;
            this.CCNameOnCard = CCNameOnCard;
            this.CCExpiryMonth = CCExpiryMonth;
            this.CCExpiryYear = CCExpiryYear;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCustomerResponse", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class UpdateCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public bool UpdateCustomerResult;
        
        public UpdateCustomerResponse() {
        }
        
        public UpdateCustomerResponse(bool UpdateCustomerResult) {
            this.UpdateCustomerResult = UpdateCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryCustomer", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class QueryCustomerRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
        public FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public long managedCustomerID;
        
        public QueryCustomerRequest() {
        }
        
        public QueryCustomerRequest(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID) {
            this.eWAYHeader = eWAYHeader;
            this.managedCustomerID = managedCustomerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryCustomerResponse", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class QueryCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public FnR.WebApi.eWay.Token.CreditCard QueryCustomerResult;
        
        public QueryCustomerResponse() {
        }
        
        public QueryCustomerResponse(FnR.WebApi.eWay.Token.CreditCard QueryCustomerResult) {
            this.QueryCustomerResult = QueryCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryCustomerByReference", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class QueryCustomerByReferenceRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
        public FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public string CustomerReference;
        
        public QueryCustomerByReferenceRequest() {
        }
        
        public QueryCustomerByReferenceRequest(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, string CustomerReference) {
            this.eWAYHeader = eWAYHeader;
            this.CustomerReference = CustomerReference;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryCustomerByReferenceResponse", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class QueryCustomerByReferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public FnR.WebApi.eWay.Token.CreditCard QueryCustomerByReferenceResult;
        
        public QueryCustomerByReferenceResponse() {
        }
        
        public QueryCustomerByReferenceResponse(FnR.WebApi.eWay.Token.CreditCard QueryCustomerByReferenceResult) {
            this.QueryCustomerByReferenceResult = QueryCustomerByReferenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPayment", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class ProcessPaymentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
        public FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public long managedCustomerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=1)]
        public int amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=2)]
        public string invoiceReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=3)]
        public string invoiceDescription;
        
        public ProcessPaymentRequest() {
        }
        
        public ProcessPaymentRequest(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription) {
            this.eWAYHeader = eWAYHeader;
            this.managedCustomerID = managedCustomerID;
            this.amount = amount;
            this.invoiceReference = invoiceReference;
            this.invoiceDescription = invoiceDescription;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPaymentResponse", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class ProcessPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FnR.WebApi.eWay.Token.CCPaymentResponse ewayResponse;
        
        public ProcessPaymentResponse() {
        }
        
        public ProcessPaymentResponse(FnR.WebApi.eWay.Token.CCPaymentResponse ewayResponse) {
            this.ewayResponse = ewayResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPaymentWithBeagle", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class ProcessPaymentWithBeagleRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
        public FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public long managedCustomerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=1)]
        public int amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=2)]
        public string invoiceReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=3)]
        public string invoiceDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=4)]
        public string cvn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=5)]
        public string ipAddress;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=6)]
        public string billingCountry;
        
        public ProcessPaymentWithBeagleRequest() {
        }
        
        public ProcessPaymentWithBeagleRequest(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription, string cvn, string ipAddress, string billingCountry) {
            this.eWAYHeader = eWAYHeader;
            this.managedCustomerID = managedCustomerID;
            this.amount = amount;
            this.invoiceReference = invoiceReference;
            this.invoiceDescription = invoiceDescription;
            this.cvn = cvn;
            this.ipAddress = ipAddress;
            this.billingCountry = billingCountry;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPaymentWithBeagleResponse", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class ProcessPaymentWithBeagleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FnR.WebApi.eWay.Token.CCPaymentResponse ewayResponse;
        
        public ProcessPaymentWithBeagleResponse() {
        }
        
        public ProcessPaymentWithBeagleResponse(FnR.WebApi.eWay.Token.CCPaymentResponse ewayResponse) {
            this.ewayResponse = ewayResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPaymentWithCVN", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class ProcessPaymentWithCVNRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
        public FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public long managedCustomerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=1)]
        public int amount;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=2)]
        public string invoiceReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=3)]
        public string invoiceDescription;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=4)]
        public string cvn;
        
        public ProcessPaymentWithCVNRequest() {
        }
        
        public ProcessPaymentWithCVNRequest(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription, string cvn) {
            this.eWAYHeader = eWAYHeader;
            this.managedCustomerID = managedCustomerID;
            this.amount = amount;
            this.invoiceReference = invoiceReference;
            this.invoiceDescription = invoiceDescription;
            this.cvn = cvn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcessPaymentWithCVNResponse", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class ProcessPaymentWithCVNResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public FnR.WebApi.eWay.Token.CCPaymentResponse ewayResponse;
        
        public ProcessPaymentWithCVNResponse() {
        }
        
        public ProcessPaymentWithCVNResponse(FnR.WebApi.eWay.Token.CCPaymentResponse ewayResponse) {
            this.ewayResponse = ewayResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryPayment", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class QueryPaymentRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment")]
        public FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public long managedCustomerID;
        
        public QueryPaymentRequest() {
        }
        
        public QueryPaymentRequest(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID) {
            this.eWAYHeader = eWAYHeader;
            this.managedCustomerID = managedCustomerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="QueryPaymentResponse", WrapperNamespace="https://www.eway.com.au/gateway/managedpayment", IsWrapped=true)]
    public partial class QueryPaymentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://www.eway.com.au/gateway/managedpayment", Order=0)]
        public FnR.WebApi.eWay.Token.ManagedTransaction[] QueryPaymentResult;
        
        public QueryPaymentResponse() {
        }
        
        public QueryPaymentResponse(FnR.WebApi.eWay.Token.ManagedTransaction[] QueryPaymentResult) {
            this.QueryPaymentResult = QueryPaymentResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface managedCreditCardPaymentSoapChannel : FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class managedCreditCardPaymentSoapClient : System.ServiceModel.ClientBase<FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap>, FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap {
        
        public managedCreditCardPaymentSoapClient() {
        }
        
        public managedCreditCardPaymentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public managedCreditCardPaymentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public managedCreditCardPaymentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public managedCreditCardPaymentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FnR.WebApi.eWay.Token.CreateCustomerResponse FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.CreateCustomer(FnR.WebApi.eWay.Token.CreateCustomerRequest request) {
            return base.Channel.CreateCustomer(request);
        }
        
        public string CreateCustomer(
                    FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, 
                    string Title, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string Suburb, 
                    string State, 
                    string Company, 
                    string PostCode, 
                    string Country, 
                    string Email, 
                    string Fax, 
                    string Phone, 
                    string Mobile, 
                    string CustomerRef, 
                    string JobDesc, 
                    string Comments, 
                    string URL, 
                    string CCNumber, 
                    string CCNameOnCard, 
                    int CCExpiryMonth, 
                    int CCExpiryYear) {
            FnR.WebApi.eWay.Token.CreateCustomerRequest inValue = new FnR.WebApi.eWay.Token.CreateCustomerRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.Title = Title;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Address = Address;
            inValue.Suburb = Suburb;
            inValue.State = State;
            inValue.Company = Company;
            inValue.PostCode = PostCode;
            inValue.Country = Country;
            inValue.Email = Email;
            inValue.Fax = Fax;
            inValue.Phone = Phone;
            inValue.Mobile = Mobile;
            inValue.CustomerRef = CustomerRef;
            inValue.JobDesc = JobDesc;
            inValue.Comments = Comments;
            inValue.URL = URL;
            inValue.CCNumber = CCNumber;
            inValue.CCNameOnCard = CCNameOnCard;
            inValue.CCExpiryMonth = CCExpiryMonth;
            inValue.CCExpiryYear = CCExpiryYear;
            FnR.WebApi.eWay.Token.CreateCustomerResponse retVal = ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).CreateCustomer(inValue);
            return retVal.CreateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.CreateCustomerResponse> FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.CreateCustomerAsync(FnR.WebApi.eWay.Token.CreateCustomerRequest request) {
            return base.Channel.CreateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.CreateCustomerResponse> CreateCustomerAsync(
                    FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, 
                    string Title, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string Suburb, 
                    string State, 
                    string Company, 
                    string PostCode, 
                    string Country, 
                    string Email, 
                    string Fax, 
                    string Phone, 
                    string Mobile, 
                    string CustomerRef, 
                    string JobDesc, 
                    string Comments, 
                    string URL, 
                    string CCNumber, 
                    string CCNameOnCard, 
                    int CCExpiryMonth, 
                    int CCExpiryYear) {
            FnR.WebApi.eWay.Token.CreateCustomerRequest inValue = new FnR.WebApi.eWay.Token.CreateCustomerRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.Title = Title;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Address = Address;
            inValue.Suburb = Suburb;
            inValue.State = State;
            inValue.Company = Company;
            inValue.PostCode = PostCode;
            inValue.Country = Country;
            inValue.Email = Email;
            inValue.Fax = Fax;
            inValue.Phone = Phone;
            inValue.Mobile = Mobile;
            inValue.CustomerRef = CustomerRef;
            inValue.JobDesc = JobDesc;
            inValue.Comments = Comments;
            inValue.URL = URL;
            inValue.CCNumber = CCNumber;
            inValue.CCNameOnCard = CCNameOnCard;
            inValue.CCExpiryMonth = CCExpiryMonth;
            inValue.CCExpiryYear = CCExpiryYear;
            return ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).CreateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FnR.WebApi.eWay.Token.UpdateCustomerResponse FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.UpdateCustomer(FnR.WebApi.eWay.Token.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomer(request);
        }
        
        public bool UpdateCustomer(
                    FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, 
                    long managedCustomerID, 
                    string Title, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string Suburb, 
                    string State, 
                    string Company, 
                    string PostCode, 
                    string Country, 
                    string Email, 
                    string Fax, 
                    string Phone, 
                    string Mobile, 
                    string CustomerRef, 
                    string JobDesc, 
                    string Comments, 
                    string URL, 
                    string CCNumber, 
                    string CCNameOnCard, 
                    int CCExpiryMonth, 
                    int CCExpiryYear) {
            FnR.WebApi.eWay.Token.UpdateCustomerRequest inValue = new FnR.WebApi.eWay.Token.UpdateCustomerRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            inValue.Title = Title;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Address = Address;
            inValue.Suburb = Suburb;
            inValue.State = State;
            inValue.Company = Company;
            inValue.PostCode = PostCode;
            inValue.Country = Country;
            inValue.Email = Email;
            inValue.Fax = Fax;
            inValue.Phone = Phone;
            inValue.Mobile = Mobile;
            inValue.CustomerRef = CustomerRef;
            inValue.JobDesc = JobDesc;
            inValue.Comments = Comments;
            inValue.URL = URL;
            inValue.CCNumber = CCNumber;
            inValue.CCNameOnCard = CCNameOnCard;
            inValue.CCExpiryMonth = CCExpiryMonth;
            inValue.CCExpiryYear = CCExpiryYear;
            FnR.WebApi.eWay.Token.UpdateCustomerResponse retVal = ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).UpdateCustomer(inValue);
            return retVal.UpdateCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.UpdateCustomerResponse> FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.UpdateCustomerAsync(FnR.WebApi.eWay.Token.UpdateCustomerRequest request) {
            return base.Channel.UpdateCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.UpdateCustomerResponse> UpdateCustomerAsync(
                    FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, 
                    long managedCustomerID, 
                    string Title, 
                    string FirstName, 
                    string LastName, 
                    string Address, 
                    string Suburb, 
                    string State, 
                    string Company, 
                    string PostCode, 
                    string Country, 
                    string Email, 
                    string Fax, 
                    string Phone, 
                    string Mobile, 
                    string CustomerRef, 
                    string JobDesc, 
                    string Comments, 
                    string URL, 
                    string CCNumber, 
                    string CCNameOnCard, 
                    int CCExpiryMonth, 
                    int CCExpiryYear) {
            FnR.WebApi.eWay.Token.UpdateCustomerRequest inValue = new FnR.WebApi.eWay.Token.UpdateCustomerRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            inValue.Title = Title;
            inValue.FirstName = FirstName;
            inValue.LastName = LastName;
            inValue.Address = Address;
            inValue.Suburb = Suburb;
            inValue.State = State;
            inValue.Company = Company;
            inValue.PostCode = PostCode;
            inValue.Country = Country;
            inValue.Email = Email;
            inValue.Fax = Fax;
            inValue.Phone = Phone;
            inValue.Mobile = Mobile;
            inValue.CustomerRef = CustomerRef;
            inValue.JobDesc = JobDesc;
            inValue.Comments = Comments;
            inValue.URL = URL;
            inValue.CCNumber = CCNumber;
            inValue.CCNameOnCard = CCNameOnCard;
            inValue.CCExpiryMonth = CCExpiryMonth;
            inValue.CCExpiryYear = CCExpiryYear;
            return ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).UpdateCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FnR.WebApi.eWay.Token.QueryCustomerResponse FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.QueryCustomer(FnR.WebApi.eWay.Token.QueryCustomerRequest request) {
            return base.Channel.QueryCustomer(request);
        }
        
        public FnR.WebApi.eWay.Token.CreditCard QueryCustomer(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID) {
            FnR.WebApi.eWay.Token.QueryCustomerRequest inValue = new FnR.WebApi.eWay.Token.QueryCustomerRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            FnR.WebApi.eWay.Token.QueryCustomerResponse retVal = ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).QueryCustomer(inValue);
            return retVal.QueryCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryCustomerResponse> FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.QueryCustomerAsync(FnR.WebApi.eWay.Token.QueryCustomerRequest request) {
            return base.Channel.QueryCustomerAsync(request);
        }
        
        public System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryCustomerResponse> QueryCustomerAsync(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID) {
            FnR.WebApi.eWay.Token.QueryCustomerRequest inValue = new FnR.WebApi.eWay.Token.QueryCustomerRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            return ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).QueryCustomerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FnR.WebApi.eWay.Token.QueryCustomerByReferenceResponse FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.QueryCustomerByReference(FnR.WebApi.eWay.Token.QueryCustomerByReferenceRequest request) {
            return base.Channel.QueryCustomerByReference(request);
        }
        
        public FnR.WebApi.eWay.Token.CreditCard QueryCustomerByReference(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, string CustomerReference) {
            FnR.WebApi.eWay.Token.QueryCustomerByReferenceRequest inValue = new FnR.WebApi.eWay.Token.QueryCustomerByReferenceRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.CustomerReference = CustomerReference;
            FnR.WebApi.eWay.Token.QueryCustomerByReferenceResponse retVal = ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).QueryCustomerByReference(inValue);
            return retVal.QueryCustomerByReferenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryCustomerByReferenceResponse> FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.QueryCustomerByReferenceAsync(FnR.WebApi.eWay.Token.QueryCustomerByReferenceRequest request) {
            return base.Channel.QueryCustomerByReferenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryCustomerByReferenceResponse> QueryCustomerByReferenceAsync(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, string CustomerReference) {
            FnR.WebApi.eWay.Token.QueryCustomerByReferenceRequest inValue = new FnR.WebApi.eWay.Token.QueryCustomerByReferenceRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.CustomerReference = CustomerReference;
            return ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).QueryCustomerByReferenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FnR.WebApi.eWay.Token.ProcessPaymentResponse FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.ProcessPayment(FnR.WebApi.eWay.Token.ProcessPaymentRequest request) {
            return base.Channel.ProcessPayment(request);
        }
        
        public FnR.WebApi.eWay.Token.CCPaymentResponse ProcessPayment(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription) {
            FnR.WebApi.eWay.Token.ProcessPaymentRequest inValue = new FnR.WebApi.eWay.Token.ProcessPaymentRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            inValue.amount = amount;
            inValue.invoiceReference = invoiceReference;
            inValue.invoiceDescription = invoiceDescription;
            FnR.WebApi.eWay.Token.ProcessPaymentResponse retVal = ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).ProcessPayment(inValue);
            return retVal.ewayResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentResponse> FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.ProcessPaymentAsync(FnR.WebApi.eWay.Token.ProcessPaymentRequest request) {
            return base.Channel.ProcessPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentResponse> ProcessPaymentAsync(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription) {
            FnR.WebApi.eWay.Token.ProcessPaymentRequest inValue = new FnR.WebApi.eWay.Token.ProcessPaymentRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            inValue.amount = amount;
            inValue.invoiceReference = invoiceReference;
            inValue.invoiceDescription = invoiceDescription;
            return ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).ProcessPaymentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleResponse FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.ProcessPaymentWithBeagle(FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleRequest request) {
            return base.Channel.ProcessPaymentWithBeagle(request);
        }
        
        public FnR.WebApi.eWay.Token.CCPaymentResponse ProcessPaymentWithBeagle(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription, string cvn, string ipAddress, string billingCountry) {
            FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleRequest inValue = new FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            inValue.amount = amount;
            inValue.invoiceReference = invoiceReference;
            inValue.invoiceDescription = invoiceDescription;
            inValue.cvn = cvn;
            inValue.ipAddress = ipAddress;
            inValue.billingCountry = billingCountry;
            FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleResponse retVal = ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).ProcessPaymentWithBeagle(inValue);
            return retVal.ewayResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleResponse> FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.ProcessPaymentWithBeagleAsync(FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleRequest request) {
            return base.Channel.ProcessPaymentWithBeagleAsync(request);
        }
        
        public System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleResponse> ProcessPaymentWithBeagleAsync(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription, string cvn, string ipAddress, string billingCountry) {
            FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleRequest inValue = new FnR.WebApi.eWay.Token.ProcessPaymentWithBeagleRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            inValue.amount = amount;
            inValue.invoiceReference = invoiceReference;
            inValue.invoiceDescription = invoiceDescription;
            inValue.cvn = cvn;
            inValue.ipAddress = ipAddress;
            inValue.billingCountry = billingCountry;
            return ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).ProcessPaymentWithBeagleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FnR.WebApi.eWay.Token.ProcessPaymentWithCVNResponse FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.ProcessPaymentWithCVN(FnR.WebApi.eWay.Token.ProcessPaymentWithCVNRequest request) {
            return base.Channel.ProcessPaymentWithCVN(request);
        }
        
        public FnR.WebApi.eWay.Token.CCPaymentResponse ProcessPaymentWithCVN(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription, string cvn) {
            FnR.WebApi.eWay.Token.ProcessPaymentWithCVNRequest inValue = new FnR.WebApi.eWay.Token.ProcessPaymentWithCVNRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            inValue.amount = amount;
            inValue.invoiceReference = invoiceReference;
            inValue.invoiceDescription = invoiceDescription;
            inValue.cvn = cvn;
            FnR.WebApi.eWay.Token.ProcessPaymentWithCVNResponse retVal = ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).ProcessPaymentWithCVN(inValue);
            return retVal.ewayResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentWithCVNResponse> FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.ProcessPaymentWithCVNAsync(FnR.WebApi.eWay.Token.ProcessPaymentWithCVNRequest request) {
            return base.Channel.ProcessPaymentWithCVNAsync(request);
        }
        
        public System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.ProcessPaymentWithCVNResponse> ProcessPaymentWithCVNAsync(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID, int amount, string invoiceReference, string invoiceDescription, string cvn) {
            FnR.WebApi.eWay.Token.ProcessPaymentWithCVNRequest inValue = new FnR.WebApi.eWay.Token.ProcessPaymentWithCVNRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            inValue.amount = amount;
            inValue.invoiceReference = invoiceReference;
            inValue.invoiceDescription = invoiceDescription;
            inValue.cvn = cvn;
            return ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).ProcessPaymentWithCVNAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FnR.WebApi.eWay.Token.QueryPaymentResponse FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.QueryPayment(FnR.WebApi.eWay.Token.QueryPaymentRequest request) {
            return base.Channel.QueryPayment(request);
        }
        
        public FnR.WebApi.eWay.Token.ManagedTransaction[] QueryPayment(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID) {
            FnR.WebApi.eWay.Token.QueryPaymentRequest inValue = new FnR.WebApi.eWay.Token.QueryPaymentRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            FnR.WebApi.eWay.Token.QueryPaymentResponse retVal = ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).QueryPayment(inValue);
            return retVal.QueryPaymentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryPaymentResponse> FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap.QueryPaymentAsync(FnR.WebApi.eWay.Token.QueryPaymentRequest request) {
            return base.Channel.QueryPaymentAsync(request);
        }
        
        public System.Threading.Tasks.Task<FnR.WebApi.eWay.Token.QueryPaymentResponse> QueryPaymentAsync(FnR.WebApi.eWay.Token.eWAYHeader eWAYHeader, long managedCustomerID) {
            FnR.WebApi.eWay.Token.QueryPaymentRequest inValue = new FnR.WebApi.eWay.Token.QueryPaymentRequest();
            inValue.eWAYHeader = eWAYHeader;
            inValue.managedCustomerID = managedCustomerID;
            return ((FnR.WebApi.eWay.Token.managedCreditCardPaymentSoap)(this)).QueryPaymentAsync(inValue);
        }
    }
}
