// <auto-generated />
namespace FnR.Databases.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TempRelationshipFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TempRelationshipFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201307190221279_TempRelationshipFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
